name: Build and Test

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with: 
          distribution: temurin
          java-version: 21
          cache: sbt
      - name: Setup sbt
        uses: sbt/setup-sbt@v1
      - name: Build and test mccct
        shell: bash
        run: sbt "clean; test"